services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_hospital_db
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hospital"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
