spring:
  application:
    name: hospital-management

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081

logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
        boot: DEBUG
        jdbc: TRACE



